import Orbifolds.Diffeology.Algebra.Module

/-!
# Internal tangent spaces

This file defines internal tangent spaces on diffeological spaces following
https://arxiv.org/abs/1411.5425; concretely, the tangent space at `x` is implemented as
a quotient of the direct sum of the domains of all plots sending `0` to `x`.

For this to be actually useful we will need to show that this agrees with the usual tangent
spaces of vector spaces and manifolds, which we have yet to do.

## Main definitions / results:
* `PreInternalTangentSpace x`: the direct sum of the domains of all plots sending `0` to `x`.
* `InternalTangentSpace x`: the internal tangent space at `x`.
* `internalTangentMap f x`: the tangent map of `f` at `x` if `f` is (globally) smooth,
  and `0` otherwise.
* `internalTangentMap_id`, `internalTangentMap_comp`: lemmas showing that this is functorial.

## TODO:
* namespace and shorten names of `InternalTangentSpace` and `internalTangentMap`,
  maybe find some good abbreviations
* tangent spaces of discrete / indiscrete spaces
* tangent spaces of open subspaces
* tangent spaces of vector spaces
* tangent spaces of manifolds
* tangent maps of constant maps
* tangent maps of maps between vector spaces / manifolds
-/

universe u v

open DirectSum DiffeologicalSpace Classical ContDiff

noncomputable section

variable {X Y Z : Type u} [DiffeologicalSpace X] [DiffeologicalSpace Y] [DiffeologicalSpace Z]

/-- The set of all plots in `X` that send `0` to `x`. -/
def DiffeologicalSpace.pointedPlots (x : X) : Set ((n : ℕ) × (Eucl n → X)) :=
  {p | IsPlot p.2 ∧ p.2 0 = x}

/-- The direct sum of the domains of all pointed plots to `x`.
The actual internal tangent space is obtained as a quotient from this. -/
def PreInternalTangentSpace (x : X) := ⨁ p : pointedPlots x, Eucl p.1.1

instance {x : X} : AddCommGroup (PreInternalTangentSpace x) := by
  unfold PreInternalTangentSpace; infer_instance

instance {x : X} : Module ℝ (PreInternalTangentSpace x) := by
  unfold PreInternalTangentSpace; infer_instance

nonrec abbrev PreInternalTangentSpace.lof {x : X} (p : pointedPlots x) :
    Eucl p.1.1 →ₗ[ℝ] PreInternalTangentSpace x :=
  lof ℝ (pointedPlots x) (fun p ↦ Eucl p.1.1) p

/-- The internal tangent space of `X` at `x`, implemented here as the quotient of
`PreInternalTangentSpace x` by the subspace generated by some relations. -/
def InternalTangentSpace (x : X) := PreInternalTangentSpace x ⧸ Submodule.span ℝ
  {v : PreInternalTangentSpace x | ∃ p q : pointedPlots x,
    ∃ f : DSmoothMap (Eucl p.1.1) (Eucl q.1.1), ∃ w : Eucl p.1.1,
      v = PreInternalTangentSpace.lof p w - PreInternalTangentSpace.lof q (fderiv ℝ f 0 w)}

instance {x : X} : AddCommGroup (InternalTangentSpace x) := by
  unfold InternalTangentSpace; infer_instance

instance {x : X} : Module ℝ (InternalTangentSpace x) := by
  unfold InternalTangentSpace; infer_instance

/-- The canonical linear map from the domain of any pointed plot into the tangent space. -/
def InternalTangentSpace.lof {x : X} (p : pointedPlots x) :
    Eucl p.1.1 →ₗ[ℝ] InternalTangentSpace x :=
  Submodule.mkQ _ ∘ₗ PreInternalTangentSpace.lof p

lemma InternalTangentSpace.lof_comp_apply {x : X} (p : pointedPlots x) {m : ℕ}
    {f : Eucl m → Eucl p.1.1} (hf : ContDiff ℝ ∞ f) (hf' : f 0 = 0) (v : Eucl m):
    lof (x := x) ⟨⟨m, p.1.2 ∘ f⟩, (isPlot_reparam p.2.1 hf:), (hf' ▸ p.2.2:)⟩ v =
      lof p (fderiv ℝ f 0 v) := by
  refine (Submodule.Quotient.eq _).2 (Submodule.subset_span ?_)
  exact ⟨⟨⟨m, p.1.2 ∘ f⟩, (isPlot_reparam p.2.1 hf:), (hf' ▸ p.2.2:)⟩, p, ⟨f, hf.dsmooth⟩, v, rfl⟩

lemma InternalTangentSpace.lof_comp {x : X} (p : pointedPlots x) {m : ℕ}
    {f : Eucl m → Eucl p.1.1} (hf : ContDiff ℝ ∞ f) (hf' : f 0 = 0) :
    lof (x := x) ⟨⟨m, p.1.2 ∘ f⟩, (isPlot_reparam p.2.1 hf:), (hf' ▸ p.2.2:)⟩ =
      lof p ∘ₗ fderiv ℝ f 0 := by
  ext v; exact lof_comp_apply p hf hf' _

/-- Transports plots from `x` to `f x` for any smooth map `f`. -/
def DiffeologicalSpace.pointedPlots_map {f : X → Y} (hf : DSmooth f) (x : X) :
    pointedPlots x → pointedPlots (f x) :=
  fun p ↦ ⟨⟨p.1.1, f ∘ p.1.2⟩, (hf.comp p.2.1.dsmooth).isPlot, by simp [p.2.2]⟩

/-- The map `PreInternalTangentSpace x →ₗ[ℝ] PreInternalTangentSpace (f x)` that
descents to the actual tangent map. Defined as `0` when `f` isn't smooth. -/
def preInternalTangentMap (f : X → Y) (x : X) :
    PreInternalTangentSpace x →ₗ[ℝ] PreInternalTangentSpace (f x) :=
  if hf : DSmooth f then
    toModule ℝ (pointedPlots x) (PreInternalTangentSpace (f x)) fun p ↦
      lof ℝ (pointedPlots (f x)) (fun p ↦ Eucl p.1.1) (pointedPlots_map hf x p)
  else 0

/-- The internal tangent map of `f` at `x` when `f` is smooth, and `0` otherwise. -/
def internalTangentMap (f : X → Y) (x : X) :
    InternalTangentSpace x →ₗ[ℝ] InternalTangentSpace (f x) :=
  Submodule.mapQ _ _ (preInternalTangentMap f x) (by
    by_cases hf : DSmooth f
    · rw [← Submodule.map_le_iff_le_comap, Submodule.map_span_le]
      intro v ⟨p, q, g, w, hv⟩
      apply Submodule.subset_span
      use pointedPlots_map hf x p, pointedPlots_map hf x q, g, w
      simp only [preInternalTangentMap, hf, ↓reduceDIte, hv, map_sub]
      -- why does simp not use `toModule_lof`? possible defeq abuse in `preInternalTangentMap`?
      convert rfl using 2 <;> symm <;> convert toModule_lof ℝ _ _ using 2
    · simp_rw [preInternalTangentMap, eq_false hf, dite_false, Submodule.comap_zero]
      exact le_top)

@[simp]
lemma pointedPlots_map_id (x : X) : pointedPlots_map dsmooth_id x = id := by
  rfl

lemma pointedPlots_map_comp {f : X → Y} {g : Y → Z} (hf : DSmooth f) (hg : DSmooth g) (x : X) :
    pointedPlots_map (hg.comp hf) x = pointedPlots_map hg (f x) ∘ pointedPlots_map hf x  := by
  rfl

@[simp]
lemma preInternalTangentMap_id (x : X) : preInternalTangentMap id x = LinearMap.id := by
  simp_rw [preInternalTangentMap, dsmooth_id, dite_true, pointedPlots_map_id, id_eq]
  apply linearMap_ext; intro p; ext x
  simp

lemma preInternalTangentMap_comp {f : X → Y} {g : Y → Z} (hf : DSmooth f) (hg : DSmooth g) (x : X) :
    preInternalTangentMap (g ∘ f) x =
      preInternalTangentMap g (f x) ∘ₗ preInternalTangentMap f x := by
  simp_rw [preInternalTangentMap, hf, hg, hg.comp hf, dite_true, pointedPlots_map_comp hf hg]
  apply linearMap_ext; intro p; ext x'
  simp_rw [LinearMap.comp_assoc, LinearMap.comp_apply, Function.comp_apply, toModule_lof]
  -- again necessary because rewriting with `toModule_lof` directly doesn't work somehow
  symm; convert toModule_lof ℝ _ _ using 2

@[simp]
lemma internalTangentMap_id (x : X) : internalTangentMap id x = LinearMap.id := by
  simp_rw [internalTangentMap, preInternalTangentMap_id]
  exact Submodule.mapQ_id _

lemma internalTangentMap_comp {f : X → Y} {g : Y → Z} (hf : DSmooth f) (hg : DSmooth g) (x : X) :
    internalTangentMap (g ∘ f) x = internalTangentMap g (f x) ∘ₗ internalTangentMap f x := by
  simp_rw [internalTangentMap, preInternalTangentMap_comp hf hg]
  exact Submodule.mapQ_comp _ _ _ _ _ _ _

/-- The canonical map from a diffeological vector space to its internal tangent space at a point
`x`, sending any vector `v` to the internal tangent vector represented by the path
`t ↦ x + t • v`. -/
def vectorSpaceToInternalTangentSpace [AddCommGroup X] [Module ℝ X] [DiffeologicalAddGroup X]
    [DSmoothSMul ℝ X] (x : X) : X →ₗ[ℝ] InternalTangentSpace x where
  toFun v := by
    refine InternalTangentSpace.lof ⟨⟨1, fun t ↦ x + (t 0) • v⟩, ?_, by simp⟩ (.single 0 1)
    -- TODO get fun_prop to handle this
    refine ((dsmooth_add_left x).comp ?_).isPlot
    refine dsmooth_smul.comp (DSmooth.prod_mk ?_ dsmooth_const)
    exact (EuclideanSpace.proj (𝕜 := ℝ) (0 : Fin 1)).dsmooth
  map_add' v w := by
    let i₁ : Eucl 1 →L[ℝ] Eucl 2 := ⟨⟨⟨fun t ↦ .single (0 : Fin 2) (t 0), fun _ _ ↦
      Pi.single_add _ _ _⟩, fun a _ ↦ Pi.single_smul _ a _⟩, (LinearMap.dsmooth _ _).continuous⟩
    let i₂ : Eucl 1 →L[ℝ] Eucl 2 := ⟨⟨⟨fun t ↦ .single (1 : Fin 2) (t 0), fun _ _ ↦
      Pi.single_add _ _ _⟩, fun a _ ↦ Pi.single_smul _ a _⟩, (LinearMap.dsmooth _ _).continuous⟩
    let p : pointedPlots x := ⟨⟨2, fun t ↦ x + t 0 • v + t 1 • w⟩, by
      -- TODO get fun_prop to handle this
      simp_rw [add_assoc]
      refine ((dsmooth_add_left x).comp (DSmooth.add ?_ ?_)).isPlot <;>
        refine dsmooth_smul.comp (DSmooth.prod_mk ?_ dsmooth_const) <;>
        exact (EuclideanSpace.proj (𝕜 := ℝ) (_ : Fin 2)).dsmooth, by simp⟩
    have h₁ := InternalTangentSpace.lof_comp_apply p i₁.contDiff (map_zero i₁) (.single 0 1)
    have h₂ := InternalTangentSpace.lof_comp_apply p i₂.contDiff (map_zero i₂) (.single 0 1)
    have h₃ := InternalTangentSpace.lof_comp_apply p (i₁ + i₂).contDiff (by simp) (.single 0 1)
    refine .trans (by congr; ext; simp [p, i₁, i₂, add_assoc]) <| h₃.trans ?_
    simp only [Function.comp_apply, ContinuousLinearMap.fderiv, ContinuousLinearMap.add_apply,
      map_add, p] at h₁ h₂ ⊢
    refine (((add_left_inj _).2 h₁).trans ((add_right_inj _).2 h₂)).symm.trans ?_
    congr <;> ext <;> simp [i₁, i₂]
  map_smul' a v := by
    let f : Eucl 1 →L[ℝ] Eucl 1 := ⟨⟨⟨fun t ↦ a • t, by simp⟩,
      by simp [smul_smul, mul_comm a]⟩, (LinearMap.dsmooth _ _).continuous⟩
    let p : pointedPlots x := ⟨⟨1, fun t ↦ x + (t 0) • v⟩, by
      -- TODO get fun_prop to handle this
      refine ((dsmooth_add_left x).comp ?_).isPlot
      refine dsmooth_smul.comp (DSmooth.prod_mk ?_ dsmooth_const)
      exact (EuclideanSpace.proj (𝕜 := ℝ) (0 : Fin 1)).dsmooth, by simp⟩
    have h := InternalTangentSpace.lof_comp_apply p f.contDiff (map_zero f) (.single 0 1)
    rw [f.fderiv] at h; rw [← map_smul]
    convert h; dsimp [p, f]; rw [smul_smul, mul_comm a]

/-- The canonical map from a fine diffeological vector space to its internal tangent space at a
point is injective.

Note that this isn't the case for arbitrary diffeological vector spaces, because e.g. any vector
space becomes a diffeological vector space with the coarse diffeology but internal tangent spaces
of coarse spaces are all trivial. -/
lemma vectorSpaceToInternalTangentSpace_injective [AddCommGroup X] [Module ℝ X]
    [IsFineDiffeology ℝ X] {x : X} : Function.Injective (vectorSpaceToInternalTangentSpace x) := by
  intro v w h; unfold vectorSpaceToInternalTangentSpace at h
  simp at h
  sorry

/-- The canonical map from a fine diffeological vector space to its internal tangent space at a
point is surjective.

I don't yet know whether this holds more generally for all diffeological vector spaces, but
wouldn't bet on it. -/
lemma vectorSpaceToInternalTangentSpace_surjective [AddCommGroup X] [Module ℝ X]
    [IsFineDiffeology ℝ X] {x : X} : Function.Surjective (vectorSpaceToInternalTangentSpace x) := by
  intro v; unfold vectorSpaceToInternalTangentSpace
  simp
  sorry

/-- The canonical isomorphism between the internal tangent space of a fine diffeological vector
space and the vector space itself, given in the backwards direction by
`vectorSpaceToInternalTangentSpace`. -/
def InternalTangentSpaceVectorSpaceEquivSelf [AddCommGroup X] [Module ℝ X] [IsFineDiffeology ℝ X]
    (x : X) : InternalTangentSpace x ≃ₗ[ℝ] X :=
  (LinearEquiv.ofBijective _ ⟨vectorSpaceToInternalTangentSpace_injective,
    vectorSpaceToInternalTangentSpace_surjective⟩).symm
